{% set data = load_setup_py_data() %}
package:
  name: "scatcluster"
  version: '{{VERSION_PLACEHOLDER}}'

about:
  home: {{ data['url'] }}
  license: {{ data['license'] }}  
  summary: {{ data.get('description') }}
  
requirements:
  build:
    - python={{ python_version }}
  run:
    - python={{ python_version }}

source:
  path: ..

build:
  script: python setup.py install
  string: py{{ python_version | replace(".", "") }}
