name: pre-commit

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install ".[dev]"
          python -m pip install pre-commit
          pip list

      - name: Lint
        run: pre-commit run --all-files --config pre-commit-hooks/.pre-commit-config.yaml
